// <auto-generated />
namespace MuscleTherapyJournal.Persitance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTreatment_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTreatment_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201604030835572_Add Treatment_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
